# Generated by Django 3.2 on 2021-04-25 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_auto_20210425_1650'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='İSİM')),
                ('email', models.CharField(max_length=120, verbose_name='E-MAİL')),
                ('phone', models.CharField(max_length=120, verbose_name='NOT')),
            ],
        ),
    ]
